resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.9"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp reference/dbsnp_138.sub.vcf.gz --standard-min-confidence-threshold-for-calling 1.0"

get_padded_bed:
  padding: 100

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

snv_indels_haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

variant_filtration:
  read_ratio: 0.2
  read_depth: 100

variant_annotator:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

detected_variants:
  file_type: "VCF"

sample_target_list:
  padding: 0

get_padded_baits:
  padding: 100
  file_format: "list"

depth_of_baits:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

depth_of_targets:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

append_id_to_gdf:
  file_type: "GDF"

get_clinical_guidelines:
  haplotype_definitions: "reference/haplotype_definitions.csv"
  haplotype_activity: "reference/haplotype_activity_score.csv"
  clinical_guidelines: "reference/clinical_guidelines.csv"
  hidden_haplotypes: "reference/hidden_haplotypes.csv"

get_interaction_guidelines:
  interaction_guidelines: "reference/interaction_guidelines.csv"

reference:
  design_bed: "reference/exons_variants_pharmacogenomics.TPMT.bed"
  design_rsid: "reference/target_rsid.TPMT.bed"
  fasta: "reference/hg19.chr6.fasta"
  fai: "reference/hg19.chr6.fasta.fai"
  dbsnp: "reference/dbsnp_138.sub.vcf.gz"

generate_pgx_report:
  analyzed_variants: "reference/analyzed_variants.txt"